### ISSUE TITLE
《关于全面推进吹奏部政治文明生态发展的建议》

### ISSUE THREAD

**Issue by Hobr** [hibikilogy/hibikilogy.github.io#16]
# ~~《关于全面推进吹奏部政治文明生态发展的建议》~~

为了给广大吹奏部~~政治学~~研究者提供一个更好的交流方式，建议给站点增加像如[Disqus](https://disqus.com/)一类的评论组件，由此推动吹奏部~~政治文明~~生态发展，让各方人士能更方便讨论吹奏部伟大复兴的历程和其中的一些学术问题。

**Comment by 97littleleaf11** [comment]
目前用的是gitalk。实际上吹水用论坛就好了，学报下的评论应该尽量避免无意义的发言。

**Comment by Hobr** [comment]
我视力不好，眼睛手动把gitalk过滤了- -
当我啥也没说
