### ISSUE TITLE
是否收录虎扑京吹群像志系列

### ISSUE THREAD

**Issue by lpzjerry** [hibikilogy/hibikilogy.github.io#28]
活跃在虎扑ACG区的吹学家梓川楓著有【[京吹群像志](https://my.hupu.com/search?fid=1580&type=undefined&q=%E4%BA%AC%E5%90%B9%E7%BE%A4%E5%83%8F%E5%BF%97&sortby=general)】系列，每篇文章介绍一个角色，目前已经有十几篇，其中有些角色是比较冷门，动画中出场不多的角色。考虑到hibikilogy收录侧重于剧情分析，不知道群像志这个偏向于考究的系列是否符合这个repository的收录标准？

**Comment by 97littleleaf11** [comment]
我觉得可以收录！目前的前端模板还是比较简单的，之后我准备改成docusaurus便于更好地分类。文章本身欢迎提PR先加进来！

**Comment by pzhlkj6612** [comment]
附一个 Bilibili 专栏文集的链接： [京吹群像志- 文集 哔哩哔哩专栏](https://www.bilibili.com/read/readlist/rl268164) 。

**Comment by hehe1111** [comment]
#63 姑且加到了网站的底部友链里
