### ISSUE TITLE
Jekyll 部署问题

### ISSUE THREAD

**Issue by gbccccc** [hibikilogy/hibikilogy.github.io#48]
本地部署时遇到警告：
```
Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `plugins: [jekyll-paginate]` in your configuration file.
```
部署后查看网页，问题体现为分页器没有生成文章列表。

查阅了 `_config.yml` ，对 jekyll-paginate 的引入使用的是 `gems: [jekyll-paginate]` 而不是警告中建议的 `plugins: [jekyll-paginate]` ，修改后即可成功部署。

但考虑到我并不是太熟悉 Jekyll ，而且目前在 github-pages 部署的页面可以正常工作，我不太清楚此配置是否应该修改？

`_config.yml` 中分页器相关配置如下：
```
# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]
```

补充：查阅了一下官方文档，Jekyll-paginate 在 Jekyll 3.0 后不再包含在标准中，我怀疑 github-pages 部署的页面使用的是 Jekyll 2.x ？

**Comment by itorr** [comment]
可以按照 `.travis.yml` 文件中的部署过程在本地部署

```
gem install jekyll
gem install jekyll-paginate
jekyll build
```

**Comment by gbccccc** [comment]
> 可以按照 `.travis.yml` 文件中的部署过程在本地部署
> 
> ```
> gem install jekyll
> gem install jekyll-paginate
> jekyll build
> ```

测试了你的建议，我这依然无法生成文章列表
我的核心问题在于 `_config.yml` 中对 `jekyll-paginate` 的引入方式：只要引入分页器使用的是 `gems: [jekyll-paginate]` 而不是 `plugins: [jekyll-paginate]`，执行 `jekyll serve` 后，警告消息和这个现象就会存在
你那边部署时是没有遇到我前面提到的警告消息吗？

我这的部署环境：
- ruby 3.2.3
- gem 3.4.19
- jekyll 4.3.2

使用 `gems: [jekyll-paginate]` 的网页效果：
![image](https://github.com/hibikilogy/hibikilogy.github.io/assets/78393470/9df188f0-0484-4bcd-be40-24153f6834a4)
使用 `gems: [jekyll-paginate]` 得到的 `_site/index.html`，`Pager` 下方本应出现由分页器生成的代码
![image](https://github.com/hibikilogy/hibikilogy.github.io/assets/78393470/79bc8090-c195-4f13-bb70-55a16abf6ca3)
