### ISSUE TITLE
关于搜索功能

### ISSUE THREAD

**Issue by lrioxh** [hibikilogy/hibikilogy.github.io#52]
自己尝试用 [lunr](https://github.com/olivernn/lunr.js/) 和 [Simple-Jekyll-Search](https://github.com/christian-fei/Simple-Jekyll-Search) 实现了下站内搜索，功能可以实现，但是有一些问题，主要是**布局样式问题**

+ 基于lunr实现了一个单独搜索页，前端结果展示与主页一致，但是分页还没做；lunr搜索结果排序相关性较高，但是对中文分词支持不太好，没有模糊搜索（比如’伞木‘搜不到但’伞‘可以

+ 基于Simple-Jekyll-Search实现了一个导航栏search bar，输入随时显示结果，但是前端没调好，很丑；Simple-Jekyll-Search基于正则没有语言问题，但是排序就是时间/字符串排序

+ 或者还可以尝试外部引擎，比如bing，这个就比较简单了，就是更新慢点；前面的独立搜索方案也有加载慢的问题，全文搜索也要占不少空间

最后，菜鸡前端调布局样式真的苦手，希望有大佬帮忙改改，参见[代码](https://github.com/lrioxh/hibikilogy.github.io/tree/master)以及[效果演示页面](https://lrioxh.github.io/hibikilogy.github.io/search/)

编：改成在导航栏实现外部搜索，独立搜索页列出两个搜索框分别用lunr和Simple-Jekyll-Search

**Comment by gbccccc** [comment]
我晚点回来也想想一下你这几个方案哪个合适
另外想问问你有遇到我另一个issue里提到的一个本地部署问题吗？非常感谢！

**Comment by lrioxh** [comment]
> 有遇到我另一个issue里提到的一个本地部署问题吗？非常感谢！

有遇到，我按照jekyll报错本地加了`plugins: [jekyll-paginate]`，不过既然线上能正常渲染，应该不重要（

btw我在我那边的线上测试页面试了下gem: 和plugins: 共存，应该正常没看出啥问题

**Comment by gbccccc** [comment]
> > 有遇到我另一个issue里提到的一个本地部署问题吗？非常感谢！
> 
> 有遇到，我按照jekyll报错本地加了`plugins: [jekyll-paginate]`，不过既然线上能正常渲染，应该不重要（
> 
> btw我在我那边的线上测试页面试了下gem: 和plugins: 共存，应该正常没看出啥问题

233333那看来不是我的问题了，我昨天又回去翻了翻文档，好像是Jekyll 3.5版本把`gem`属性改成了`plugins`。

另外关于你的这几个方案，除了外部搜索引擎方案我觉得不太好以外，我觉得都有可取之处，想了想可以感觉融合一下。

这个是我关于搜索功能的 Navigation 设想：
1. 主页效果基本不变，上方增加一个 Navigation bar
2. 搜索时即时生成结果，点击结果可以直接跳转到文章
3. 如果不点击，而是敲击enter（或点击“搜索”按钮），跳转到搜索结果页，结果页应该与主页的视觉效果保持一致
4. 具体的搜索实现看你觉得哪个方案更方便就行

另外 jekyll-paginate 的分页比较僵硬，应该是不适用于搜索结果的排序的。如果要引入对搜索结果的分页的话，我感觉最好干脆把 jekyll-paginate 踢出这个项目，重新实现分页。

不知道你觉得我上面说得有没有道理（？

**Comment by lrioxh** [comment]
> 每次我 commit 都要注意把 _config.yml 的修改取消掉

我觉得其实可以直接commit上得了哈哈，我那里`gems: [jekyll-paginate]`和`plugins: [jekyll-paginate]`都在，线上本地都没啥问题；另外config不常改的话可以不add或者干脆ignore掉（

> 关于搜索功能的 Navigation 设想

这个是很合理的搜索功能实现，我尝试实现的时候遇到了包括布局样式的一些问题，比如`搜索时即时生成部分结果，点击结果可以直接跳转到文章`这个，实现效果对不同屏幕，横屏和竖屏，很容易出现错位（我前端太菜了）；然后lunr的中文分词不好意味着，比如搜`伞木`和`伞木希美`都没有结果，这太怪了233（因为不是常见中文词，lunr也可以用jieba或其他分词库，但是这个一般是在服务器上跑的）；Simple-Jekyll-Search正则匹配不以相关度优先其实也很反直觉，搜索范围限制在标题+tag到可以胜任，这个可以加上；

所以我权衡实用性考虑提了外部搜索引擎的pr，后续可能在调好样式后加上正则搜索标题+tag的`即时生成部分结果`，主要是马上吹3开播了，先实现一版方便新朋友

> 外部搜索引擎方案我觉得不太合适

我比较好奇为啥233，用外部搜索的静态网站其实不少，比如 [openssl](https://www.openssl.org/)。当然bing界面是有点乱，google或duckduckgo会整洁不少，但是不方便墙内。[以google为例](https://www.google.com.hk/search?q=site%3Ahibikilogy.github.io+%E4%BC%9E%E6%9C%A8%E5%B8%8C%E7%BE%8E)

**Comment by gbccccc** [comment]
关于搜索的原理，其实我的了解不是很深，具体实现我实在给不了什么建议（捂脸），所以我上面给出的也仅仅是 Navigation 的设计建议。但是具体的搜索效果我觉得倒是可以慢慢迭代，毕竟即使是那些真正的商业软件/论坛的搜索功能还有很多也都是纯纯依托答辩，啥都搜不到（点名百度贴吧）

关于外部搜索引擎，我只是本能地觉得，引入一个外部搜索引擎对一个网站而言，总感觉会有些突兀，当然可能也只是个人偏见吧。另外google和github的“墙”还是有不小差距的，我自己上github的时候也不是开真的梯子，所以即使要用这个方案，也还是继续用bing吧。

顺便感慨一下，吹3要开播了这个仓库终于又活跃起来了233333

**Comment by lrioxh** [comment]
我是后端选手，纯静态搜索也是现学现卖233

我是建议先合了bing的用着，功能上肯定比静态搜索完备。后续转站内静态搜索的话，我至少得解决一下布局样式问题

TODO: 
+ 横竖屏兼容的联想结果展示栏
+ 页面间消息传递，用于跳转搜索结果页
+ 搜索结果list超长隐藏
+ 尝试预载分词文件

~~最近忙春招，有没有前端大佬help一下（~~

**Comment by lrioxh** [comment]
又尝试了下可以通过trick加空格让junr实现相对合理的结果，虽然从精确找文章的角度不如外部引擎，至少看着不奇怪了

但是不知道什么时候改好，所以还是建议先合了bing的用着（

~~ps，我去nju，我隔壁seu的233333~~

**Comment by gbccccc** [comment]
> 又尝试了下可以通过trick加空格让junr实现相对合理的结果，虽然从精确找文章的角度不如外部引擎，至少看着不奇怪了
> 
> 但是不知道什么时候改好，所以还是建议先合了bing的用着（
> 
> ~ps，我去nju，我隔壁seu的233333~

草，原来是车大的兄弟23333333
我没有合并权限，你可以喊一下 @NozoMizore7

**Comment by NozoMizore7** [comment]
已合并
