### ISSUE TITLE
申请加入长期贡献

### ISSUE THREAD

**Issue by jiazengp** [hibikilogy/hibikilogy.github.io#56]
可以帮助收集一些吹学文章和网站设计与开发o((>ω< ))o
<img src="https://github.com/hibikilogy/hibikilogy.github.io/assets/86162890/0890146a-9dab-487b-9a82-443ca16ed69c" alt="Image" width="80" height="80">

**Comment by jiazengp** [comment]
@NozoMizore7

**Comment by NozoMizore7** [comment]
已邀请
