### ISSUE TITLE
feat: 关于使用 vuepress2 重构项目想法

### ISSUE THREAD

**Issue by jiazengp** [hibikilogy/hibikilogy.github.io#57]
建议使用 [Vuepress 2](https://github.com/vuepress/core) 的 [Gungnir v2](https://github.com/Renovamen/vuepress-theme-gungnir) （[v2-vuepress-theme-gungnir.vercel.app](https://v2-vuepress-theme-gungnir.vercel.app/)）主题重构网站项目，这个主题与现有网站主题基本一致而且拥有但不限于对现有功能和markdown的支持并且基本上可以无缝迁移，并且使用了 vuepress2 做为驱动。相对于[Jekyll](http://jekyllcn.com/) 不论是构建性能还是社区插件的做都的相对更好一下，并且具有以下特性
- vuepress 使用 Vue 和 Vue Router 驱动的单页面应用 (SPA）具有更好的开发体验和构建性能并且可以支持Clear URL
- 更好的架构与项目结构，更少的代码与配置可以更专注于文档。如果需要开发扩展页面或者layout也很方便
- 深色和浅色模式：使用主题切换器进行系统主题检测，以根据用户偏好设置主题
- 更好的 SEO
- 全站搜索
- PWA支持
- 目录支持
- Tex 支持 （[Katex](https://github.com/KaTeX/KaTeX))
- 在 Markdown 中轻松绘制图表和图形：[Chart.js](https://www.chartjs.org/)、[美人鱼](https://mermaid-js.github.io/)
- Markdown 增强功能：
	- 脚注（[markdown-it-footnote](https://github.com/markdown-it/markdown-it-footnote))
	- 标记 （[markdown-it-mark](https://github.com/markdown-it/markdown-it-mark))
	- 分析（[Google Analytics](https://analytics.google.com/)和[百度同济](https://tongji.baidu.com/))
	- 评论（[Giscus](https://github.com/giscus/giscus))
- RSS订阅
- 阅读时间
- 多语言支持（英语、简体中文）
- 带有标签和链接的存档页面
- 等等

如果可以的话，我可以在稍晚几天提交完整的重构 PR

**Comment by jiazengp** [comment]
@NozoMizore7 你觉得呢φ(*￣0￣)

**Comment by NozoMizore7** [comment]
@inchei @97littleleaf11  @jiazengp 交流方式见：https://github.com/hibikilogy?view_as=member
