### ISSUE TITLE
关于部署相关问题

### ISSUE THREAD

**Issue by jiazengp** [hibikilogy/hibikilogy.github.io#58]
1. 现部署域名（github.io）在国内部分地区DNS污染严重，访问困难速度慢并且已被国内大多平台拉黑
 	建议解决方案：使用自注册域名，配置解析并使用多平台同步部署例如vercel,[Netlify](https://vuepress.github.io/zh/guide/deployment.html#netlify)等

**Comment by NozoMizore7** [comment]
改网址可能还是要 @inchei 做主？
个人意见是当前网址用了很多年了，已经形成了一定口碑效应，从这一点考虑不建议修改。如果非要改，仍应以确保网址的长期有效为最优先事宜，最好是使用同样可靠的（因此最好是免费的）域名。至于可访问性相比而言就随缘吧。

**Comment by jiazengp** [comment]
个人认为 其实不仅从访问问题还是从品牌方面还是网站长远发展的角度继续与github page强绑定并不是一个好的选择，因为github page只支持单域名的静态部署限制太大。至于以前的网址可以直接重定向到新域名影响不会太大，而一个好的域名不但可以方便记忆也利于seo和建立口碑
